#!/bin/bash

echo ###############################
echo Digite a localizacao do arquivo de iplist
echo ###############################
read IPLIST
echo
for ip in $(cat $IPLIST)

do
  ping -c1 $ip &> /dev/null
  if [ $? -eq 0 ]
  then
  echo $ip is OK
  else
  echo $ip is NOT OK
  fi
done
